name: Upload assets

on:
  release:
    types: [ published ]

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  publish:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - macos-13  # Intel Mac
          - macos-latest  # Arm64

    runs-on: ${{ matrix.os }}

    name: Publish CFA for ${{ matrix.os }}

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Setup Java'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23
          cache: 'maven'

      - name: 'Run Maven'
        run: |
          mvn -B -DskipTests package

      - name: 'Upload Release Asset'
        uses: AButler/upload-release-assets@v3.0
        with:
          release-tag: ${{ github.ref_name }}
          files: "target/cfa-*.zip"
          repo-token: ${{ github.token }}
